language: node_js
node_js:
    - "0.10"
services:
    - couchdb
env:
    global:
        - NODE_ENV=test
before_install:
    - git clone git://github.com/cozy/cozy-data-system.git
    - cd cozy-data-system
    - npm install forever coffee-script -g
    - npm install # data-system
    - pwd
    - NAME=data-system TOKEN=token forever start -o forever-ds.log build/server.js
    - ps aux | grep server.js
    - sleep 5
    - cat forever-ds.log
    - sudo netstat -plunt
    - curl http://localhost:9101/
    - coffee commands.coffee test-install webdav
    - cd ..
    - export NAME=webdav
    - export TOKEN=apptoken

after_install:
    - cd node_modules/cozy-jsdav-fork/
    - npm install
    - cd ../..

after_failure:
    - cat cozy-data-system/forever-ds.log
    - curl -X POST --user proxy:token http://localhost:9101/request/user/all/
