language: node_js
node_js:
    - "0.10"
    - "0.8"
services:
    - couchdb
env:
    global:
        - NODE_ENV=test
before_install:
    - git clone git://github.com/mycozycloud/cozy-data-system.git
    - cd cozy-data-system
    - npm install forever coffee-script -g
    - npm install # data-system
    - pwd
    - forever start -o forever-ds.log server.js
    - ps aux | grep server.js
    - sleep 5
    - cat forever-ds.log
    - sudo netstat -plunt
    - curl http://localhost:9101/
    - coffee commands.coffee test-install webdav
    - cd ..
    - export NAME=webdav
    - export TOKEN=apptoken

after_install:
    - cd node_modules/jsDAV
    - npm install
    - cd ../..

after_failure:
    - cat cozy-data-system/forever-ds.log
